M48
; DRILL file {KiCad 7.0.1-3b83917a11~172~ubuntu22.04.1} date ma 24 jul 2023 14:12:15
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-24T14:12:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-3b83917a11~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X25.0Y-46.0
T2
X17.5Y-63.0
X25.0Y-36.54
X32.5Y-62.992
T0
M30
